# MATLAB/Octave matrices

MATLAB/Octave treats all variables as matrices.
- A vector (or array) is a special form of a matrix and contains only one row or one column.
- A scalar is a matrix with only one row and one column.

## Creating a scalar or vector
A scalar can be created in MATLAB/Octave as follows:

In [13]:
a = 23

a =  23


A matrix with only one row is called a row vector. A row vector can be created in MATLAB/Octave as follows (note the commas):

In [14]:
rowvec = [12, 14, 63]

rowvec =

   12   14   63



Here the commas are optional, and for simplicity, they may be skipped:

In [15]:
rowvec = [12 14 63]

rowvec =

   12   14   63



A matrix with only one column is called a column vector. A column vector can be created in MATLAB/Octave as
follows (note the semicolons):

In [16]:
colvec = [13; 45; -2]

colvec =

   13
   45
   -2



## Addressing vector elements

A vector element is addressed by an integer index enclosed in parentheses. For example:

In [17]:
x=[10 20 30 40 50 60];

In [18]:
x(3)

ans =  30


Note that MATLAB/Octave is one-based, that is, indexing starts at 1.

## Useful commands for vectors
| Command | Meaning |
| :-      | :-      |
| `x = start:end` | create row vector `x` starting with `start`, increasing by one, ending at `end` |
| `x = start:increment:end` | create row vector `x` starting with `start`, increasing by `increment`, ending at or before `end` |
| `x= linspace(start,end,number)` | create row vector `x` starting with `start`, ending at `end`, having `number` elements |
|`length(x)`|returns the length of vector `x`|
|`y = x'`   | transpose of vector `x`|

Try yourself. For example:

In [19]:
x = 10:5:40

x =

   10   15   20   25   30   35   40



In [20]:
x'

ans =

   10
   15
   20
   25
   30
   35
   40



## Creating a matrix

A matrix can be created in MATLAB/Octave as follows (note the spaces and semicolons):

In [21]:
matrix = [1 2 3; 4 5 6; 7 8 9]

matrix =

   1   2   3
   4   5   6
   7   8   9



A semicolon `;`acts as a row separator, while a space or a comma `,` acts a a column separator.

## Extracting a sub-matrix

<img src="octave_screenshot_matrix.png"/>

A portion of a matrix can be extracted and stored in a smaller matrix by specifying the names of both matrices and the rows and columns to extract. The syntax is:

`sub_matrix = matrix(r1:r2,c1:c2);` where
- `r1, r2`: beginning and ending rows
- `c1, c2`: beginning and ending columns

Extract a scalar:

In [2]:
A = [4 10 1 6 2; 8 1.2 9 4 25; 7.2 5 7 1 11; 0 0.5 4 5 56; 23 83 13 0 10] 

A =

    4.00000   10.00000    1.00000    6.00000    2.00000
    8.00000    1.20000    9.00000    4.00000   25.00000
    7.20000    5.00000    7.00000    1.00000   11.00000
    0.00000    0.50000    4.00000    5.00000   56.00000
   23.00000   83.00000   13.00000    0.00000   10.00000



In [3]:
A(2, 4)

ans =  4


Extract a vector or sub-matrix:
<img src="octave_screenshot_sub-matrices.png"/>

In [4]:
A(3, 1)

ans =  7.2000


In [5]:
A(4:5, 2:3)

ans =

    0.50000    4.00000
   83.00000   13.00000



In [6]:
A(1:5, 5)

ans =

    2
   25
   11
   56
   10



Alternatively, for a full column or row, just use a colon `:`:

In [7]:
A(:, 5)

ans =

    2
   25
   11
   56
   10



## Scalar-matrix operations
For addition, subtraction, multiplication, and division of a matrix by a scalar, the operation is applied to all elements of the matrix.

For example:

In [8]:
A = [ 1 2; 3 4]

A =

   1   2
   3   4



In [9]:
B = 2*A - 1

B =

   1   3
   5   7



Each element in the matrix A is multiplied by 2. Then 1 is subtracted from it.

## Useful commands for matrices
| Command | Meaning |
| :-      | :-      |
| `zeros(n)`    | creates an `n x n` matrix of zeros |
| `zeros(m, n)` | creates an `m x n` matrix of zeros |
| `ones(n)`     | creates an `n x n` matrix of ones  |
| `ones(m, n)`  | creates an `m x n` matrix of ones  |
| `size(A)` | for an `m x n` matrix `A`, returns the row vector `[m, n]` containing the number of rows and columns in matrix|
| `length(A)`| returns the larger of the number of rows or columns in `A`|
| ` B = A'` | transpose of matrix `A`|

## Try yourself

Scalar expansion:

In [10]:
w = [1 2; 3 4] + 5

w =

   6   7
   8   9



Creating sequences by using the colon `:`operator:

In [11]:
x = 1:5

x =

   1   2   3   4   5



In [12]:
y = 2:-0.5:0

y =

    2.00000    1.50000    1.00000    0.50000    0.00000



Utility functions for creating matrices:

In [13]:
z = ones(2,4)

z =

   1   1   1   1
   1   1   1   1



## Element-by-element operations
For element-wise multiplication, division and exponentiation of matrices the corresponding operator must be preceded by a dot.

| Operation      | Algebraic form | MATLAB/Octave|
| :-             | :-:            | :-:          |
| Addition       | $a + b$        | `a + b`      |
| Subtraction    | $a - b$        | `a - b`      |
| Multiplication | $a\;b$         | `a .* b`     |
| Division       | $a : b$        | `a ./ b`     |
| Exponentiation | $a^b$          | `a.^b`       |

Note that matrix addition and subtraction is element-wise by definition.

For example:

In [14]:
x = [ 1 2 3 ];

In [15]:
y = [ 4 5 6 ];

In [16]:
z = x .* y

z =

    4   10   18



Each element in x is multiplied by the corresponding element in y.

## Matrix, vector and array
<img src="figure_vector_matrix_array.png"/>

In programming jargon, an n-dimensional field of values is called an *array*:

- vector: one-dimensional array
- matrix: two-dimensionl array
- arrays can b multi-dimensional

## Exercise
Now you are ready to tackle the following exercise: 
[Getting started with MATLAB/Octave](https://seafile.zfn.uni-bremen.de/f/55ce9869f68a4efb92c3/)

## Structure arrays
Structure arrays allow to store data of different types and sizes in fields.
- Each field represents a property or attribute of the data.
- All fields together form a hierarchy that reflects the layers of the data in a logical manner.